--[[ require("globals") ]]
require("user.options")
require("user.keymaps")
require("user.autocommands")
require("user.plugins")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.bufferline")
require("user.lualine")
require("user.indentline")
require("user.whichkey")
require("user.gps")
require("user.refactoring")
require("user.hop")
require("user.lsp")
